### ISSUE TITLE
Add Codenet language classifier Model

### ISSUE THREAD

**Issue by ckadner** [machine-learning-exchange/katalog#38]
Thanks @kmh4321 for working on this!

**Tasks:**
- [x] create the model source repo on Github, with REST API and Dockerfile
- [x] build and push the Docker image
- [x] add the Model YAML to the katalog repo
- [x] add the Model to the Bootstrapper and Quickstart in the `mlx` repo
- [x] fix up the README (fill in place holders)

**Comment by ckadner** [comment]
FYI @romeokienzler

**Comment by kmh4321** [comment]
Pushed to Dockerhub: 
https://hub.docker.com/repository/docker/codait/codenet-language-classifier

**Comment by kmh4321** [comment]
Created PR for katalog repo and fixed the README. 

@ckadner can you take care of step 4: ` add the Model to the Bootstrapper and Quickstart in the mlx repo`

**Comment by ckadner** [comment]
All done. Thanks @kmh4321
